# Generated by Django 6.0.1 on 2026-01-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionCliente',
            fields=[
                ('idatencion', models.AutoField(db_column='idAtencion', primary_key=True, serialize=False)),
                ('fechaatencion', models.DateTimeField(db_column='fechaAtencion')),
                ('tiposolicitud', models.CharField(db_column='tipoSolicitud', max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'db_table': 'tb_atencion_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('nivel', models.CharField(blank=True, default='Nuevo', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'tb_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('idinteraccion', models.AutoField(db_column='idInteraccion', primary_key=True, serialize=False)),
                ('montogasto', models.DecimalField(blank=True, db_column='montoGasto', decimal_places=2, max_digits=10, null=True)),
                ('fechahoraregistro', models.DateTimeField(db_column='fechaHoraRegistro')),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'db_table': 'tb_interacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('idjuego', models.AutoField(db_column='idJuego', primary_key=True, serialize=False)),
                ('nombrejuego', models.CharField(db_column='nombreJuego', max_length=100)),
                ('categoria', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Juego',
                'verbose_name_plural': 'Juegos',
                'db_table': 'tb_juegos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.AutoField(db_column='idPromocion', primary_key=True, serialize=False)),
                ('nombrepromocion', models.CharField(db_column='nombrePromocion', max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechainicio', models.DateField(db_column='fechaInicio')),
                ('fechafin', models.DateField(db_column='fechaFin')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'tb_promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('idvisita', models.AutoField(db_column='idVisita', primary_key=True, serialize=False)),
                ('fechavisita', models.DateField(db_column='fechaVisita')),
                ('horavisita', models.TimeField(db_column='horaVisita')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'tb_visitas',
                'managed': False,
            },
        ),
    ]
