# Generated by Django 6.0.1 on 2026-01-26 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('RECARGA_TARJETA', 'Recarga Tarjeta (Tragamonedas)'), ('COMPRA_FICHAS', 'Compra de Fichas (Mesas)'), ('CONSUMO', 'Consumo Bar/Restaurante')], default='RECARGA_TARJETA', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='crm_api.cliente')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
                'db_table': 'tb_transacciones',
            },
        ),
    ]
