# Generated by Django 6.0.2 on 2026-02-06 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencioncliente',
            options={'managed': True, 'verbose_name': 'Atención', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cliente',
            field=models.ForeignKey(db_column='idCliente', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='crm_api.cliente'),
            preserve_default=False,
        ),
    ]
